const data = [
  {
    id: 1,
    title: 'Portfolio',
    description: 'In this project I build a portfolio website using Javascript, HTML and CSS based on a design from a Figma file.',
    image: 'img/projects/portfolio.png',
    link: 'https://rega1237.github.io/',
  },
  {
    id: 2,
    title: 'Crypto Convention',
    description: 'This is a page of a conference based on a template, I used HTML, CSS and Javascript to develop this page',
    image: 'img/projects/crypto_convention.png',
    link: 'https://rega1237.github.io/cap-crypto/index.html',
  },
  {
    id: 3,
    title: 'Pokedex',
    description: 'Pair programming project where we create a webpage can see your favorite pokemon, like them, see valuable stats and add comments.',
    image: 'img/projects/pokedex.png',
    link: 'https://rega1237.github.io/Pokedex-Javascript/',
  },
  {
    id: 4,
    title: 'To do list',
    description: 'A to-do list app where you can add to-dos and remove completed ones. Developed using Javascript, HTML and CSS.',
    image: 'img/projects/to_do.png',
    link: 'https://rega1237.github.io/to-do-list/',
  },
  {
    id: 5,
    title: 'Math Magicians',
    description: 'Math Magicians is a single page application (SPA) where the user can do simple calculations, this project was made with react JS.',
    image: 'img/projects/math.png',
    link: 'https://6298d7c0130dd1405ca22ecd--keen-belekoy-fc163b.netlify.app/',
  },
  {
    id: 6,
    title: 'Book Store',
    description: 'Book Store is a SPA built with React where you can display a list of books, add a book and delete a book.',
    image: 'img/projects/bookstore.png',
    link: 'https://bookcreator.herokuapp.com/',
  },
  {
    id: 7,
    title: 'Space Travelers',
    description: 'Web app build in pair programming using react and redux to store and apply actions the data fetched from the API.',
    image: 'img/projects/space_hub.png',
    link: 'https://spiffy-marigold-45bbb6.netlify.app/',
  },
  {
    id: 8,
    title: 'Monitor Crypto',
    description: 'Project build using react to fetch and show the top 100 crypto list from API of Poloinex.',
    image: 'img/projects/monitor_crypto.png',
    link: 'https://monitor-crypto-mobile.herokuapp.com/',
  },
  {
    id: 9,
    title: 'School Library',
    description: 'Application built in ruby based on a school library where books can be rented by teachers or students. You can add books, students, teachers.',
    image: 'img/projects/school_library.png',
    link: 'https://github.com/rega1237/OOP-school-library',
  },
  {
    id: 10,
    title: 'SpendLess App',
    description: 'In this project I build a portfolio website using Javascript, HTML and CSS based on a design from a Figma file.',
    image: 'img/projects/spendless.png',
    link: 'https://spendless-rails.herokuapp.com/',
  },
  {
    id: 11,
    title: 'Home Stadium',
    description: 'In this project I build a portfolio website using Javascript, HTML and CSS based on a design from a Figma file.',
    image: 'img/projects/home_stadium.png',
    link: 'https://homestadium.netlify.app/login',
  },
];

export default data;
